app_s5/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import savename, readmatkul
app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('savename', savename),
    path('readmatkul/', views.readmatkul, name='readmatkul'),
    #url(r'^delete/(?P<part_id>[0-9]+)/$', views.delete_matkul, name='delete_view'),
    path('delete/<pk>', views.matkul_delete, name='matkul_delete'),
    path('detail/<pk>', views.detailmatkul, name='detailmatkul'),
    path('detail_matkul/', views.detail_matkul, name='detail_matkul')
]

project_s5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_s5.urls')),
]

app_s5/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model):
    display_name = models.CharField(max_length=30, unique=True)
    sks = models.CharField(max_length=2)
    
    
    

app_s5/forms.py
from django import forms
from .models import Matkul

class Input_Form(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['display_name','sks']
        
    error_messages = {
        'required' : 'Please enter value'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'Nama Matkul'
    }
    input_attrs1 = {
        'placeholder' : 'Jumlah SKS'
    }

    display_name = forms.CharField(label='', required=True, 
    max_length=27, widget=forms.TextInput(attrs=input_attrs))
    
    
    sks = forms.CharField(label='', required=True, 
    max_length=27, widget=forms.TextInput(attrs=input_attrs1))

app_s5/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import Matkul
from .forms import Input_Form

def home(request):
    response = {'input_form':Input_Form}
    return render(request, 'main/home.html', response)

def readmatkul(request):
    response = {'input_form':Input_Form}
    matkuls = Matkul.objects.all()
    response['matkuls'] = matkuls
    return render(request, 'main/readmatkul.html', response)

def savename(request):
    form = Input_Form(request.GET or None)
    if (form.is_valid and request.method == 'GET'):
        form.save()
        return HttpResponseRedirect('/')
        
"""
def delete_matkul(request, part_id=None):
    object = Matkul.objects.get(id=part_id)
    object.delete()
    return render(request, 'main/home.html')
"""

def matkul_delete(request, pk):
    matkul = get_object_or_404(Matkul, pk=pk)  # Get your current matkul
    response = {'input_form':Input_Form}
    matkuls = Matkul.objects.all()
    response['matkuls'] = matkuls
    if request.method == 'POST':         # If method is POST,
        matkul.delete()                     # delete the matkul.
                                       # Finally, redirect to the homepage.

    return render(request, 'main/readmatkul.html', response)

def detail_matkul(request):
    response = {'nama', 'sks'}
    return render(request, 'main/detail_matkul.html', response)

def detailmatkul(request,pk):
    matkul = get_object_or_404(Matkul, pk=pk)
    response = {'nama':matkul.display_name, 'sks':matkul.sks}
    return render(request, 'main/detail_matkul.html', response)

app_s5/templates/main/detail_matkul.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ nama }}</title>
    </head>
    <body>
    <table width="33%">
    <tr>
        <th>Matkul</th>
        <th>SKS</th>
    </tr>
    <tr>
    <td>{{ nama }}</td>
    <td align="center">{{ sks }}</td>
     </tr>
    </table>
</br>
    <table>
    <tr>
        <th><a href="{% url 'main:readmatkul' %}"><button>Back</button></a></th>
        <th><a href="{% url 'main:home' %}"><button>Home</button></a></th>
    </tr>
    </table>
    </body>
</html>

app_s5/templates/main/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Form Pengisian</title>
    </head>
    <body>
    Masukkan data matkul yang kamu pilih
    <form action="savename" method="GET">
        {% csrf_token %}
    {{input_form.as_p}}
    <input type = "submit" value="Submit">
    </form>
</br>
    <a href="{% url 'main:readmatkul' %}"><button>Lihat Matkul</button></a>
    </body>
</html>

app_s5/templates/main/readmatkul.html
<!DOCTYPE html>
<html>
    <head>
        <title>Daftar Matkul</title>
    </head>
    <body>
    <table width="33%">
    <tr>
        <th>Matkul</th>
    </tr>
    {% if matkuls %}
        {% for matkul in matkuls %}
        <tr>
        <td><a href ="{% url 'main:detailmatkul' matkul.id %}">{{ matkul.display_name }}</td>
        <td><form action="{% url 'main:matkul_delete' matkul.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete matkul">
            </form>
        </td>
        </tr>
        {% endfor %}
    {% endif %} 
    </table>
    <a href="{% url 'main:home' %}"><button>Back</button>
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>